### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Variable'

### ISSUE THREAD

**Issue by a-palamarchuk** [hmgoforth/gps_denied_uav_localization#3]
Running the code with the recent versions of the libraries gives me an error

`AttributeError: 'function' object has no attribute 'Variable'`

in DeepLKBatch on the lines like

`if isinstance(p, torch.autograd.variable.Variable):`

The problem is fixed by converting the reference to `torch.autograd.Variable`. See https://github.com/lanpa/tensorboardX/issues/100

Even if the original authors are not going to fix it, I hope the information will help those who try to use their code.

**Comment by imtoba** [comment]
Hey thanks for the fix! Did you make it work for your own dataset by any chance?

**Comment by patrickpoirier51** [comment]
@Boreas7 thanks for this, but still have some issues:
Try to run with
torch                   1.4.0  (with Cuda 10.1)
torchvision             0.5.0

And when loading model:
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 0 in sequence argument at position #1 'tensors'

So I modified DeepLKBatch.py with:
#USE_CUDA = torch.cuda.is_available()
USE_CUDA = False

An then:
Traceback (most recent call last):
  File "pose_opt.py", line 1804, in <module>
    sliding_window_opt(args)
  File "pose_opt.py", line 1404, in sliding_window_opt
    M_tmpl = extract_map_templates(P_mk, M, T, img_c, img_h, img_w)
  File "pose_opt.py", line 1125, in extract_map_templates
    M_warp_tens, _ = dlk.warp_hmg(M_tens, P_mk_tens)
  File "../deep_feat/DeepLKBatch.py", line 143, in warp_hmg
    xy = torch.cat((X.view(1, X.numel()), Y.view(1, Y.numel()), Variable(torch.ones(1, X.numel()))), 0)
RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 2 in sequence argument at position #1 'tensors'

How did you worked around this ?
